# Generated by Django 6.0.5 on 2026-05-12 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_attempt',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_block_time',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_created_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pending_email',
        ),
    ]
